#!/bin/sh
# Everything the Xcode project needs before its first build.
#
# Both of these are produced by build phases too, but xcodebuild resolves the
# framework reference and the source file list before any phase runs — so on a
# clean checkout the first build fails without them.
set -e
cd "$(dirname "$0")/.."

echo "Building the shared framework…"
./gradlew :shared:assembleSharedReleaseXCFramework

echo "Writing the API keys…"
props="local.properties"
out="ios/Lexicon/Support/Keys.generated.swift"
read_key() {
  [ -f "$props" ] || return 0
  grep "^$1=" "$props" | head -1 | cut -d= -f2- | tr -d ' \r'
}
cat > "$out" <<SWIFT
// Generated by the "Generate keys" build phase. Do not edit, do not commit.
enum Keys {
    static let pexels = "$(read_key pexels.apiKey)"
    static let pixabay = "$(read_key pixabay.apiKey)"
}
SWIFT

echo "Ready. Open ios/Lexicon.xcodeproj, or build with SKIP_GRADLE=1 xcodebuild …"
