#!/usr/bin/env python3
"""Ranks every corpus entry by how often Polish uses it, from KWJP.

Run from anywhere:  python3 tools/vocabulary/build_frequency.py

Reads
    tools/vocabulary/.cache/kwjp100-*.csv.gz   see kwjp.py
    tools/vocabulary/corpus/**/*.tsv        the entries to rank

Writes
    tools/vocabulary/frequency.tsv          polish, english, ARF per million words

Then run build_assets.py, which turns the ARF into each entry's frequency rank and fills
the Top N presets from it.

The rank used to be the line order of core.tsv, an estimate written by hand, and the
entries added from Tatoeba had none. A word is ranked by its lemma, so bać się counts
every form of bać; a phrase of two or three words by how often that exact sequence
occurs. Longer phrases and words KWJP never saw are left unranked.
"""

from __future__ import annotations

import sys

import kwjp
import sgjp
from build_examples import TOOLS, corpus_entries

FREQUENCY = TOOLS / "frequency.tsv"


def sequence(text: str) -> tuple[str, ...]:
    return tuple(word.lower() for word in text.replace(",", " ").split())


def main() -> int:
    entries = corpus_entries()
    try:
        lemmas = kwjp.lemma_frequency()
        wanted = {sequence(e["word"]) for e in entries if 1 < len(sequence(e["word"])) <= 3}
        ngrams = {**kwjp.ngram_frequency(2, wanted), **kwjp.ngram_frequency(3, wanted)}
    except FileNotFoundError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    lines = ["# Generated by build_frequency.py from KWJP (CC BY 4.0). Columns: polish <TAB> english <TAB> ARF."]
    ranked = 0
    for entry in entries:
        words = sequence(entry["word"])
        if entry["pos"] == "v":
            lemma, before, after = sgjp.verb_lemma(entry["word"].lower())
            arf = lemmas.get(lemma) if not before and after in ("", " się") else ngrams.get(words)
        elif len(words) == 1:
            arf = lemmas.get(words[0])
        else:
            arf = ngrams.get(words)
        if arf:
            lines.append(f"{entry['word']}\t{entry['gloss']}\t{arf:.2f}")
            ranked += 1
    FREQUENCY.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"frequency.tsv: {ranked} of {len(entries)} entries ranked")
    return 0


if __name__ == "__main__":
    sys.exit(main())
