#!/usr/bin/env python3
"""Writes a stock-photo search phrase for every shipped word, using OpenAI.

Run from anywhere:  python3 tools/vocabulary/build_pictures.py

Reads
    local.properties                        openai.apiKey
    tools/vocabulary/corpus/**/*.tsv        the words
    tools/vocabulary/examples.tsv           each word's example sentence, as context

Writes
    tools/vocabulary/pictures.tsv           word, gloss, phrase

Then run build_assets.py to fold pictures.tsv into vocabulary_pl.json.

The app used to search for pictures by the bare English gloss, so "lilac" found the
colour, "right" found anything, and "without" found nothing useful at all. The phrase
names what a photo should show for this one sense. Where no
photo could show on its own, the phrase pictures the situation of its example sentence,
so every word and phrase has something to show.

Phrases are cached in tools/vocabulary/.pictures-cache.json. Pass --refresh to ask again.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from build_examples import BATCH, TOOLS, BuildError, api_key, corpus_entries, entry_key, entry_lines, read_tsv, request

PICTURES = TOOLS / "pictures.tsv"
CACHE = TOOLS / ".pictures-cache.json"

PROMPT = """For each Polish vocabulary entry below, write the English search phrase that finds
a stock photo a learner would connect with that meaning.

Rules:
* Two to five plain English words, the way people search a photo site.
* Name something a camera can capture: an object, animal, place, or a person doing
  something. Add the detail that rules out other senses of the same spelling:
  bez "lilac" is "lilac flowers in bloom", never the colour; zamek "lock" is "door lock".
* Every entry gets a phrase. For a word no photo can show on its own - grammar words,
  degree words, abstract ideas - picture the situation its example sentence describes,
  so the photo carries the sentence rather than the bare word:
  bez "without", "Idę bez kurtki." -> "person walking in shirt sleeves".
  bardzo "very", "Bardzo lubię kawę." -> "woman enjoying coffee".
  trzeba "one must" -> "person checking a to-do list".
* Never answer with text, letters, signs or writing in the photo.

Return ONLY a JSON object mapping each entry number, as a string, to its phrase.

Entries, one per line, as "number | word | meaning | part of speech | topics | example":

{{entries}}
"""


def examples() -> dict[str, str]:
    path = TOOLS / "examples.tsv"
    if not path.exists():
        return {}
    return {f"{cols[0]}\t{cols[1]}": cols[2] for cols in read_tsv(path) if len(cols) >= 3}


def ask(key: str, entries: list[dict]) -> dict[str, str]:
    prompt = PROMPT.replace("{{entries}}", entry_lines(entries, ["word", "gloss", "pos", "topics", "example"]))
    answer = request(key, prompt)
    return {
        entry_key(entries[int(n) - 1]): phrase.strip()
        for n, phrase in answer.items()
        if isinstance(phrase, str) and phrase.strip() and n.isdigit() and 0 < int(n) <= len(entries)
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh", action="store_true", help="ignore the cache and ask again for everything")
    arguments = parser.parse_args()

    try:
        key = api_key()
    except BuildError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    cache: dict[str, str] = {}
    if CACHE.exists() and not arguments.refresh:
        cache = json.loads(CACHE.read_text(encoding="utf-8"))

    sentences = examples()
    words = corpus_entries()
    for entry in words:
        entry["example"] = sentences.get(entry_key(entry), "")

    pending = [e for e in words if entry_key(e) not in cache]
    print(f"{len(words)} corpus words, {len(pending)} to ask")
    try:
        for start in range(0, len(pending), BATCH):
            batch = pending[start : start + BATCH]
            written = ask(key, batch)
            for entry in batch:
                phrase = written.get(entry_key(entry))
                if isinstance(phrase, str):
                    cache[entry_key(entry)] = phrase.strip()
            print(f"  {min(start + BATCH, len(pending))}/{len(pending)}", end="\r", flush=True)
            CACHE.write_text(json.dumps(cache, ensure_ascii=False, indent=0, sort_keys=True), encoding="utf-8")
        print()
    except BuildError as error:
        CACHE.write_text(json.dumps(cache, ensure_ascii=False, indent=0, sort_keys=True), encoding="utf-8")
        print(f"error: {error}", file=sys.stderr)
        return 1

    lines = ["# Generated by build_pictures.py. Columns: polish <TAB> english <TAB> photo search phrase (empty: no picture)."]
    pictured = 0
    for entry in words:
        if entry_key(entry) in cache:
            lines.append(f"{entry['word']}\t{entry['gloss']}\t{cache[entry_key(entry)]}")
            pictured += bool(cache[entry_key(entry)])
    PICTURES.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"pictures.tsv: {pictured} words with a phrase, {len(lines) - 1 - pictured} with none")
    if pictured < len(words):
        print("every word should have one; run again to fill the rest in")
    missing = sum(1 for e in words if entry_key(e) not in cache)
    if missing:
        print(f"{missing} words got no reply; run again to fill them in")
    return 0


if __name__ == "__main__":
    sys.exit(main())
