#!/usr/bin/env python3
"""Writes a stock-photo search phrase for every shipped word, using OpenAI.

Run from anywhere:  python3 tools/vocabulary/build_pictures.py

Reads
    local.properties                        openai.apiKey
    tools/vocabulary/corpus/**/*.tsv        the words
    tools/vocabulary/examples.tsv           each word's example sentence, as context

Writes
    tools/vocabulary/pictures.tsv           word, gloss, phrase

Then run build_assets.py to fold pictures.tsv into vocabulary_pl.json.

The app used to search for pictures by the bare English gloss, so "lilac" found the
colour, "right" found anything, and "without" found nothing useful at all. The phrase
names what a photo should show for this one sense, and is left empty when no ordinary
photo would make the meaning recognisable: the app then shows no picture rather than
a misleading one.

Phrases are cached in tools/vocabulary/.pictures-cache.json. Pass --refresh to ask again.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from build_examples import BATCH, TOOLS, BuildError, api_key, corpus_entries, entry_key, entry_lines, read_tsv, request

PICTURES = TOOLS / "pictures.tsv"
CACHE = TOOLS / ".pictures-cache.json"

UNPICTURABLE = {"prep", "conj", "part", "prn", "interj"}

PROMPT = """For each Polish vocabulary entry below, decide whether a stock photo can show
its meaning, and if it can, write the English search phrase that finds that photo.

Answer "yes" only when a learner shown a typical photo for your phrase would guess
this exact meaning. Answer "no" for meanings a photo cannot pin down: grammar words,
degree words, states of being, abstract ideas and most adverbs.
  być "to be": no.  bardzo "very": no.  bez "without": no.  wolność "freedom": no.
  bez "lilac": yes, "lilac flowers in bloom" (never the colour).
  zamek "lock": yes, "door lock".  biegać "to run": yes, "person jogging in park".

The phrase: two to five plain English words, the way people search a photo site,
naming something a camera can capture, with the detail that rules out other senses.

Return ONLY a JSON object mapping each entry number, as a string, to an object
{"visual": "yes" or "no", "phrase": "..."}. Leave the phrase empty for "no".

Entries, one per line, as "number | word | meaning | part of speech | topics | example":

{{entries}}
"""


def examples() -> dict[str, str]:
    path = TOOLS / "examples.tsv"
    if not path.exists():
        return {}
    return {f"{cols[0]}\t{cols[1]}": cols[2] for cols in read_tsv(path) if len(cols) >= 3}


def ask(key: str, entries: list[dict]) -> dict[str, str]:
    prompt = PROMPT.replace("{{entries}}", entry_lines(entries, ["word", "gloss", "pos", "topics", "example"]))
    answer = request(key, prompt)
    phrases = {}
    for n, reply in answer.items():
        if not (n.isdigit() and 0 < int(n) <= len(entries)) or not isinstance(reply, dict):
            continue
        visual = str(reply.get("visual", "")).strip().lower() == "yes"
        phrases[entry_key(entries[int(n) - 1])] = str(reply.get("phrase", "")).strip() if visual else ""
    return phrases


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh", action="store_true", help="ignore the cache and ask again for everything")
    arguments = parser.parse_args()

    try:
        key = api_key()
    except BuildError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    cache: dict[str, str] = {}
    if CACHE.exists() and not arguments.refresh:
        cache = json.loads(CACHE.read_text(encoding="utf-8"))

    sentences = examples()
    words = corpus_entries()
    for entry in words:
        entry["example"] = sentences.get(entry_key(entry), "")

    for entry in words:
        if entry["pos"] in UNPICTURABLE:
            cache[entry_key(entry)] = ""
    pending = [e for e in words if entry_key(e) not in cache]
    print(f"{len(words)} corpus words, {len(pending)} to ask")
    try:
        for start in range(0, len(pending), BATCH):
            batch = pending[start : start + BATCH]
            written = ask(key, batch)
            for entry in batch:
                phrase = written.get(entry_key(entry))
                if isinstance(phrase, str):
                    cache[entry_key(entry)] = phrase.strip()
            print(f"  {min(start + BATCH, len(pending))}/{len(pending)}", end="\r", flush=True)
            CACHE.write_text(json.dumps(cache, ensure_ascii=False, indent=0, sort_keys=True), encoding="utf-8")
        print()
    except BuildError as error:
        CACHE.write_text(json.dumps(cache, ensure_ascii=False, indent=0, sort_keys=True), encoding="utf-8")
        print(f"error: {error}", file=sys.stderr)
        return 1

    lines = ["# Generated by build_pictures.py. Columns: polish <TAB> english <TAB> photo search phrase (empty: no picture)."]
    pictured = 0
    for entry in words:
        if entry_key(entry) in cache:
            lines.append(f"{entry['word']}\t{entry['gloss']}\t{cache[entry_key(entry)]}")
            pictured += bool(cache[entry_key(entry)])
    PICTURES.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"pictures.tsv: {pictured} words with a phrase, {len(lines) - 1 - pictured} with none")
    missing = sum(1 for e in words if entry_key(e) not in cache)
    if missing:
        print(f"{missing} words got no reply; run again to fill them in")
    return 0


if __name__ == "__main__":
    sys.exit(main())
